DATA:
  data_folder: ../data
  dataset_name: ac4-triplet
  if_artifact_aug: false
  if_blur_aug: true
  if_blurenhanced_aug: false
  if_dilate: false
  if_elastic_aug: false
  if_ema_flip: true
  if_ema_intensity: true
  if_ema_mask: true
  if_filp_aug: true
  if_intensity_aug: true
  if_mask_aug: true
  if_misalign_aug: true
  if_missing_aug: false
  if_mixup_aug: false
  if_noise_aug: true
  if_rotation_aug: true
  if_scale_aug: false
  if_sobel_aug: false
  max_kernel_size: 9
  max_noise_std: 0.2
  max_sigma: 2
  min_kernel_size: 3
  min_noise_std: 0.01
  min_sigma: 0
  padding: 80
  shift_channels: null
  test_split: 20
  train_split: 80
  widen_way: true
MODEL:
  bn_mode: async
  decode_ratio: 1
  filters:
  - 32
  - 64
  - 128
  - 256
  if_sigmoid: true
  if_skip: 'False'
  init_mode: kaiming_normal
  init_mode_mala: kaiming
  input_nc: 1
  merge_mode: cat
  model_type: superhuman_devo-t3_triplet-MSE_shallow
  output_nc: 1
  pad_mode: zero
  relu_mode: elu
  upsample_mode: transposeS
NAME: ab5_bdy_embed_feat_2nd
TEST:
  model_name: ''
  pad: 0
TRAIN:
  base_lr: 0.0001
  batch_size: 4
  decay_iters: 100000
  display_freq: 100
  end_lr: 0.0001
  if_cuda: true
  if_edge_discrepancy: false
  if_edge_relation: true
  if_neighbor: false
  if_node: true
  if_seg: true
  if_valid: true
  if_verse: false
  load_path: null
  loss_aff_ema_embed: 1.0
  loss_aff_ema_feat: 1.0
  loss_aff_ema_func: null
  loss_aff_embed: 1.0
  loss_aff_feat: 1.0
  loss_aff_func: null
  loss_discriminative_embed: 1.0
  loss_discriminative_feat: 1.0
  loss_discriminative_func: null
  loss_func: WeightedBCELoss
  loss_graph_aff: 10.0
  loss_graph_edge: 0.1
  loss_graph_embed: 1.0
  loss_graph_feat: 1.0
  loss_graph_func: null
  loss_graph_node: 0.1
  loss_lambda_embed: 1.0
  loss_lambda_feat: 1.0
  loss_lambda_func: L1Loss
  loss_motion_embed: 1.0
  loss_motion_feat: 1.0
  loss_motion_func: MotionLoss2
  loss_motion_interp: 2
  loss_motion_iter: 20000
  loss_smooth_embed: 0.1
  loss_smooth_feat: 0.1
  loss_smooth_func: WeightedSmoothLoss
  loss_smooth_interp: 2
  loss_smooth_iter: 20000
  model_id: 200000
  num_workers: 4
  opt_type: adam
  pad: 0
  power: 1.5
  random_seed: 42
  resume: false
  save_freq: 1000
  save_path: ../models/
  separate_weight: true
  total_iters: 200000
  valid_freq: 1000
  warmup_iters: 0
  weight_decay: null
